version: "3.7"

services:

  php:
    image: php:7.4-fpm
    volumes:
      - ~/localstacktry/src:/var/www/html
      - ~/localstacktry/docker/php.ini:/usr/local/etc/php/php.ini
     
  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ~/localstacktry/src:/var/www/html
      - ~/localstacktry/docker/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  composer:
    image: composer:2.0
    command: ["composer", "update"]
    working_dir: /var/www/src/composer
    volumes:
      - ~/localstacktry/src/composer:/var/www/src/composer
    depends_on:
      - web
  
  localstack:
    image: localstack/localstack:0.11.0
    container_name: localstack
    ports:
      - "4563-4599:4563-4599"
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - /tmp/localstack:/tmp/localstack,mode=600
      - /var/run/docker.sock:/var/run/docker.sock
